- name: generate sasl_passwd.db for postfix
  command: postmap /etc/postfix/sasl_passwd
  notify: restart postfix

- name: restart postfix
  service: name=postfix state=restarted

- name: restart sshd
  service: name=ssh state=restarted

- name: restart sudo
  service: name=sudo state=restarted

- name: restart UFW
  shell: yes y | ufw enable

- name: restart fail2ban
  service: name=fail2ban state=restarted
