---

- name: ensure log directory
  action: file dest=${webapps_dir}/${app_name}/log state=directory

- name: install hdf4 dev packages
  action: apt pkg=$item state=installed
  with_items:
    - libhdf4-dev

- name: install pyhdf-0.8.3
  action: pip name=http://downloads.sourceforge.net/project/pysclint/pyhdf/0.8.3/pyhdf-0.8.3.tar.gz virtualenv=${webapps_dir}/${app_name}/venv virtualenv_site_packages=yes state=present
  environment: ${pyhdf_env}

- name: deploy code from repository
  action: git repo=$repo_url dest=${webapps_dir}/${app_name}/src remote=$repo_remote version=$repo_version

- name: install dependencies into virtualenv
  action: pip requirements=${webapps_dir}/${app_name}/src/requirements.txt virtualenv=${webapps_dir}/${app_name}/venv state=present

- name: install app as module
  action: pip name=${webapps_dir}/${app_name}/src/ virtualenv=${webapps_dir}/${app_name}/venv extra_args="-U" state=present

- name: create supervisor program config
  action: template src=supervisor.ini dest=/etc/supervisor/${app_name}.ini
  notify:
    - reload supervisor
    - restart app

- name: create nginx site config
  action: template src=nginx_site.conf dest=/etc/nginx/sites-available/${app_name}.conf
  notify:
    - restart nginx

- name: link nginx config
  action: file src=/etc/nginx/sites-available/${app_name}.conf dest=/etc/nginx/sites-enabled/${app_name}.conf state=link
